# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Artwork.create(name: 'Saurien', artist: 'Alexander Calder', location: '590 Madison Avenue', history: '1975: Sprawling its neon-orange legs across the street in midtown Manhattan, Alexander Calder’s outdoor sculpture Saurien marks the entrance to the IBM building and provides an eye-catching contrast to the glassy gray skyscraper. Since it obstructs the direct pathway to the doors of the building, the structure, called a “stabile,” forces passersby on the street to choose—walk around the 30-foot-high work of art or simply walk through it. The pointy spines that surmount this spider-like, asymmetric structure attract the attention of the passersby upward, just as the surrounding buildings do.', avatar_file_name: 'Calder_Saurien.jpg', lat: 40.762288, lng:  -73.972361)
Artwork.create(name: 'Red Cube', artist: 'Isamu Noguchi', location: '140 Broadway', history: '1968: Isamu Noguchi’s Red Cube in Lower Manhattan was installed in 1968. The diagonal lines of red painted steel stand in contrast to the stark horizontal and vertical lines of the adjacent Marine Midland Building (by architect Gordon Bunshaft). The cylindrical hole running upward through the piece, as well as the cube’s topmost point, draw the viewer’s eye skyward.', avatar_file_name: 'Noguchi_Red_Cube.jpg', lat: 40.708666, lng:  -74.010148)
Artwork.create(name: 'Sunken Garden', artist: 'Isamu Noguchi', location: 'Chase Manhattan Plaza, 28 Liberty Street, New York, NY', history: '1961 - 1964: Sunken Garden is situated in the open plaza in front of the Chase Manhattan Bank building. The base of the garden is set one story below street level in a circular space cut out from the plaza. This opening in the plaza is bordered on top by a metal railing, allowing viewers to stand comfortably at the edge and look into the sculpted space below. The space is surrounded on all sides by floor to ceiling windows, allowing the garden to be seen from the inside, and opening up the lower level of the building to the outdoors.', avatar_file_name: 'Noguchi_Sunken_Garden.jpg', lat: 40.707766, lng: -74.008769)
Artwork.create(name: 'Face of Liberty', artist: 'Zachary Landsberg', location: "Governor's Island", history: 'Face of Liberty" by Zachary Landsberg, a full-scale replica of Lady Liberty, emerging face up from the ground. Viewers will be able to approach the fiberglass sculpture and see the iconic statue from a new perspective.', avatar_file_name: 'Landsberg_FaceOfLiberty.jpg', lat: 40.704146, lng: -74.008715)
Artwork.create(name: 'Hope', artist: 'Robert Indiana', location: '222 West 53rd Street, New York, NY', history: '2009: Robert Indiana created this piece in 2008 in the same style as his famous sculpture Love. Hope Day was inspired by artist Robert Indiana’s 2010 interview with The Today Show, in which he said, “I’d like to cover the world with HOPE.” He believes that, as with the iconic Robert Indiana work LOVE, which became a symbol of positivity during the turbulent 1960s, four letters can change the world. And he arranges them in such a way as to make them inescapable. Robert Indiana created HOPE in 2009 with the belief that the world was ready for a new message. HOPE suggests light and illuminates a path to a better world. The “O” in HOPE leans forward, propelling us to look forward to the promise of a better, more peaceful future.', avatar_file_name: 'Indiana_Hope.jpg', lat: 40.763358, lng: -73.982849)
Artwork.create(name: 'Needle Threading A Button', artist: 'Pentagram Architectural Services', location: '7th Avenue and 39th Street, New York, NY', history: '1996: Designed as part of the Fashion Center Information Kiosk designed by Pentagram Architectural Services in 1996 and inspired by Claes Oldenburg’s sculptures.', avatar_file_name: 'Needle.jpg', lat: 40.754341, lng: -73.987809)